#!/usr/bin/env bash
#setting up the header to identify
#which server is serving / responding
#and setting up the server by installing nginx

apt update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
if [ "$(pgrep -c nginx)" -le 0 ]; then
                service nginx start
        else
                service nginx restart
fi

curl -H "X-Served-By:264-web-02" 35.170.74.216
