#!/usr/bin/env bash
# Install and configure HAproxy on load balace server

apt-get -y install haproxy

# edit config file
load_balance_config=\
"
frontend http
  bind *:80
  mode http
  default_backend web-backend

backend web-backend
   balance roundrobin
   mode http
   server 264-web-01 35.237.36.195:80 check
   server 264-web-02 35.170.74.216:80 check
"
 echo "$load_balance" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
